name: Build All Actions

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.7.0'

      - name: Npm Build
        id: npm-build
        run: |
          npm install
          npm run build
          VERSION=$(node -p "require('./package.json').version")
          echo "Built version $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$VERSION"

      - uses: tool3/ncc@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          src: 'src/index.ts'
          branch: 'main'
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist/

      - name: Bump version and push tag
        if: github.ref == 'refs/heads/main'
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ steps.npm-build.outputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
